### ISSUE TITLE
Zope 4 ZMI: Clean up hardcoded list of items that don't want the add dialog

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#540]
Followup to https://github.com/zopefoundation/Zope/pull/536

Clear out items from the hardcoded list `no_modal_dialog` inside `zmi/styles/resources/zmi_base.js` when the affected products implement the new class-variable based solution and those are released:

- [x] https://github.com/zopefoundation/AccessControl/issues/82 for `manage_addUserFolder`
  - [x] released
  - [x] Zope versions configuration updated
  - [x] removed from `zmi/styles/resources/zmi_base.js`
- [x] https://github.com/zopefoundation/Products.CMFCore/issues/72 for `manage_addRegistry`
  - [x] removed from `zmi/styles/resources/zmi_base.js`
- [x] https://github.com/zopefoundation/Products.SiteErrorLog/issues/19 for `manage_addErrorLog`
  - [x] removed from `zmi/styles/resources/zmi_base.js`
- [x] https://github.com/zopefoundation/Products.PluggableAuthService/issues/37 for `addPluggableAuthService`
  - [x] removed from `zmi/styles/resources/zmi_base.js`
