### ISSUE TITLE
Zope 4 ZMI: Add i18n support for the ZMI

### ISSUE THREAD

**Issue by macagua** [zopefoundation/Zope#631]
Are any plan for adding i18n support for the Zope Products from ZMI?

A example real and usefull, it is Django project, that have support for i18n from Django Admin Interface.

**Comment by tech-kio** [comment]
Being able to use i18n in Products at all would be a good start. I don't seem to be able to figure-out how to activate i18n for Chameleon PageTemplates. Do we need to create a child PageTemplate and do some magic? In Zope 2 we used sx.translations but it does not support Zope 4. What is the i18n situation? Maybe only a little doc would go a long way. Simple to use and implicit i18n is much needed. Tx very much for your comments!

**Comment by icemac** [comment]
@tech-kio `zope.i18n` should work well together with `Zope`, see the Plone documentation how to use it, it should be possible to apply it to plain Zope: https://docs.plone.org/develop/plone/i18n/internationalisation.html

@macagua I do not see through the web editing of translations as one of the core businesses of Zope. Maybe it could be done in a separately developed Product.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-5-16 23:30 -0700:
> ...
>@macagua I do not see through the web editing of translations as one of the core businesses of Zope. Maybe it could be done in a separately developed Product.

@macagua
Typically, the product itself would handle its translations (which it can
do already now without through the web support).
Local control is only necessary if a local translation (not delivered
with the product) should be integrated or some translations should
be locally overridden. Those can also be done on the "zcml" level
and likely the need is sufficiently seldom that through the web
support might not be necessary.
Have a look at "https://pypi.org/project/Products.PlacelessTranslationService/".

**Comment by tech-kio** [comment]
Thanks for your comments. Problem is, we have multi-sites setups and we don't want to create products for each and every domain we host. I see that PTS is using i18n/ subfolder so maybe we can stuff all our translation domain .mo files in there and restart, every time someone makes a change. Not ideal. If I understand the meaning of Placeless, it means translation domains would be global? For PTS I guess I should go to their github home and report the issues about incompatibilities with Zope 4/Python 3:

https://github.com/plone/Products.PlacelessTranslationService

in:
Products/PlacelessTranslationService/utils.py

#from UserDict import UserDict
from collections import UserDict

also bombs (!) with "patches" in:
Products/PlacelessTranslationService/__init__.py

# # Apply import time patches
if not bool(os.getenv('DISABLE_PTS')):
    import patches

Personnally I preferred sx.translations which was using the standard locales/fr/LC_MESSAGES layout but it seems to be abandoned for a very long time.

'trying hard to move in Zope 4/Python3/unicode world. Thank very much for your help!

**Comment by d-maurer** [comment]
tech-kio wrote at 2019-5-17 10:12 -0700:
>Problem is, we have multi-sites setups and we don't want to create products for each and every domain we host. I see that PTS is using i18n/ subfolder so maybe we can stuff all our translation domain .mo files in there and restart, every time someone makes a change. Not ideal.

It looks as if you have quite special requirements.
From my point of view, special requirements justify special solutions.

I am quite confident, that looking at the code of the translation
machinery, you will find a way to reinitialize it (e.g. in order to
adapt to changes) without the need to restart your site.
You might even be able to recognize (most) changes automatically
and make them effective without manual intervention.

**Comment by macagua** [comment]
I think it does not explain me well, what I propose:

The ZMI offers a GUI with user messages in _English_ by default, below an example: https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/dbMain.dtml#L8

Shows by default the following message **"The Database Manager allows you to view database status information."**

My comment is that this type of user messages can be translated into another language, for example into _Spanish_ **"El Administrador de base de datos le permite ver la información de estado de la base de datos."** using i18n support techniques to the Zope 4 ZMI code.

If the Django admin interface supports i18n within its own user interface and supports translations in several languages, then my question is:

Why does the Zope 4 administration interface itself not support its own interface translated into other languages?

**Comment by dataflake** [comment]
It just doesn't. It has not had support for automated translations for the ZMI in its entire near 20 year history, and it has never been an issue as far as I am aware.

You're welcome to write code for it and create a pull request.

**Comment by tech-kio** [comment]
OK, so easy... It works with zope.i18n out-of-the-box.

After creating my language domain in a product and compiled my .po files into their respective dirs locales/fr/LC_MESSAGES, the only thing missing it seems was the "magic" to initialize "target_language" in the context :

<html lang="fr" xmlns:tal="http://xml.zope.org/namespaces/tal" xmlns:i18n="http://xml.zope.org/namespaces/i18n" i18n:domain="mydomain" tal:define="target_language python:'fr'">

This is because by default:
target_language: <NoneType - at 0x890790>

So it seems that language domains are global, and Chameleon responds implicitly already. Very Nice.

No need for PTS or the multitude of other i18n related things that I first tried from pypi!

So what's left for me is a question of sniffing the language of the browser, put-it in the SESSION and transferring this value to request['target_language'] in the header of my PageTemplates or, since I already have my PageTemplate descendant, I should be able to simply assign target_language in the request through the __call__, calling render afterwards.

Sorry for bumping-in and thanks all for your guidance in my understanding.

**Comment by macagua** [comment]
@dataflake it great to read that, dou you have any suggest?, for example, just make a fork with a new git branch called **"zmi-i18n-support"** and from this staring the coding, right?

I am sorry, I want following the correct steps for integrate this improvement to ZMI.

**Comment by dataflake** [comment]
@macagua Yes, that's what you would normally do. What you name your branch doesn't really matter. I tend to name branches after the issue tracker issue number, like "issue_123".

tech-kio's hint about using the `zope.i18n` package may get you most of the way there for all those ZMI views that are page template based.

**Comment by d-maurer** [comment]
tech-kio wrote at 2019-5-18 11:03 -0700:
> ...
>So what's left for me is a question of sniffing the language of the browser, put-it in the SESSION and transferring this value to request['target_language'] in the header of my PageTemplates or, since I already have my PageTemplate descendant, I should be able to simply assign target_language in the request through the __call__, calling render afterwards.

Zope typically uses a utility to handle (e.g.) the request's
"Accept-Charset". When I remember right, then it is
a utility for the interface `IPreferedLanguages` (or similarly named).

**Comment by icemac** [comment]
@d-maurer wrote:
> Zope typically uses a utility to handle (e.g.) the request's "Accept-Charset". When I remember right, then it is a utility for the interface `IPreferedLanguages` (or similarly named).

I think you are speaking of `zope.i18n.interfaces.IUserPreferredLanguages`. There is an adapter for this interface registered here:
https://github.com/zopefoundation/Zope/blob/e6a85acc02b12d349db96b487027b138fb897cbc/src/ZPublisher/i18n.zcml#L10-L14

It is used to set the locale on the request, so it should be accessible like this : `request.locale`.
The returned object provides the `ILocale` interface, see:
https://github.com/zopefoundation/zope.i18n/blob/8b62b3b3592c3133b30e08d48e057cf248e20448/src/zope/i18n/interfaces/locales.py#L597-L645

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-5-19 23:14 -0700:
>@d-maurer wrote:
>> Zope typically uses a utility to handle (e.g.) the request's "Accept-Charset". When I remember right, then it is a utility for the interface `IPreferedLanguages` (or similarly named).
>
>I think you are speaking of `zope.i18n.interfaces.IUserPreferredLanguages`.

Indeed.

>It is used to set the locale on the request, so it should be accessible like this : `request.locale`.
>The returned object provides the `ILocale` interface, see:
>https://github.com/zopefoundation/zope.i18n/blob/8b62b3b3592c3133b30e08d48e057cf248e20448/src/zope/i18n/interfaces/locales.py#L597-L645

I have looked at `zope.i18n.translate` (which likely is used
by the "PageTemplate" translation machinery and maybe other parts
which need translations). Apparently, it determines
the target language not directly via an `IUserPreferredLanguages`
utility but via an `zope.i18n.interfaces.INegotiator` utility.
It also requires that `zope.i18n.config.ALLOWED_LANGUAGES` has been set
up (from the envvar `zope_i18n_allowed_languages`).

**Comment by macagua** [comment]
## Updating 2019-05-22

### About the i18n syntax

I am using the [zope.i18nmessageid](https://github.com/zopefoundation/zope.i18nmessageid) package for define the MessageFactory for the new domain called " Zope" into the [Zope](https://github.com/zopefoundation/Zope) and [Products.TemporyFolder](https://github.com/zopefoundation/Products.TemporyFolder) packages, until the moment, later going to the Zope ecosystem packages.

For the dtml template, I am using the **dtml-translate** tag inspired in the way used from [ZWiki](https://github.com/simonmichael/ZWiki) package.

### About the gettext scripts

I was working with create a gettext extraction strings into a bash script and I was stop my work for improvement it, like the **plone.app.locales** package and I found the [zope.app.locales](https://github.com/zopefoundation/zope.app.locales) package with a extraction util incluided. Well I will continue the work integating **zope.app.locales** package, maybe is a elegant and practice way to distribute the translation.




### TODO tasks

- [x] i18n syntax for the [Zope](https://github.com/zopefoundation/Zope) package
- [x] i18n syntax for the [Products.TemporyFolder](https://github.com/zopefoundation/Products.TemporyFolder) package
- [ ] i18n syntax for the [Products.CMFCore](https://github.com/zopefoundation/Products.CMFCore) package
- [ ] i18n syntax for the [Products.ExternalMethod](https://github.com/zopefoundation/Products.ExternalMethod) package
- [ ] i18n syntax for the [Products.MailHost](https://github.com/zopefoundation/Products.MailHost) package
- [ ] i18n syntax for the [Products.PythonScripts](https://github.com/zopefoundation/Products.PythonScripts) package
- [ ] i18n syntax for the [Products.Sessions](https://github.com/zopefoundation/Products.Sessions) package
- [ ] i18n syntax for the [Products.SiteErrorLog](https://github.com/zopefoundation/Products.SiteErrorLog) package
- [ ] integrate the Zope domain translations again into the [zope.app.locales](https://github.com/zopefoundation/zope.app.locales) package see https://github.com/zopefoundation/Zope/commit/7669068cb17e2439ff63d42579f8d6e68ea9bc9f

**Comment by icemac** [comment]
I am not sure if `zope.app.locales` is the right place to store the translations of the ZMI. As @hannosch said in 7669068: „Zope2 uses almost none of the translations provided in the package“. This is still true for Zope 4. Maybe we should have an extra package for the ZMI of Zope and the ecosystem.

**Comment by icemac** [comment]
@macagua Are you still working on this issue?

**Comment by icemac** [comment]
There has been silence on this issue for about 2 years now, so I am closing it.
Feel free to reopen if you are still planning to work on it.
