### ISSUE TITLE
Drop Python 2 support code

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#692]
- [X] Grep for `2.7` and drop the Python 2 support code (#699)
- [X] Grep for `PY2` and drop the Python 2 support code (#699)
- [X] Grep for `PY3` and drop the Python 2 support code (#700)
- [x] Grep for `sys.version` resp. `sys.version_info` and drop the Python 2 support code (#701)
- [x] Grep for `Python 2` and drop the Python 2 support code (#704)
- [x] Grep for `Py2` and `Py3` and drop the Python 2 support code
- [x] Drop dependency on `six` (#705)
- [x] check `__future__` imports
- [x] check `__unicode__` methods
- [x] check `__str__` methods to make sure they return native strings
- [x] run [pyupgrade](https://github.com/asottile/pyupgrade) with `--py3-plus`
- [X] update `python_requires` and `classifiers` in `setup.py`  (89fff4c2c60d468ce9474266e6416cfd3811a844)
- [x] review `except`s and especially `except ImportError:` for Python 2 support code

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-8-28 23:20 -0700:
>- [ ] Grep for `2.7`, `PY2`, `Python 2` and drop the Python 2 support code
>- [ ] Drop dependency on `six`

You likely should also watch out also for `PY3`. Sometimes
I (and maybe others) have branched on `PY3` rather than `PY2`.

**Comment by icemac** [comment]
@d-maurer Thank you for the input, I additionally added other possible hints for Python 2 support code.

**Comment by hugovk** [comment]
You can also:

* [ ] grep for `sys.version_info` and drop the Python 2 support code
* [ ] check `__future__` imports
* [ ] run [pyupgrade](https://github.com/asottile/pyupgrade) with `--py3-plus`
* [ ] update `python_requires` and `classifiers` in `setup.py`
* [ ] review `except`s and especially `except ImportError:` for Python 2 support code

**Comment by icemac** [comment]
@hugovk Thank you for your suggestions, I'll copy them to the description of the issue.

**Comment by dataflake** [comment]
Made some progress in 06d940ff5c48cbec764d8b03d5f519437db2d239

**Comment by dataflake** [comment]
With the changes in #724 there's just one thing from the original list left. We have a couple `__str__` implementations that will return `bytes` instead of `str`.

**Comment by dataflake** [comment]
I added more tests in 163b20ac02a0547b0cf9262c21fc5e43ccdefb2a to test all remaining ``__str__`` implementations. This is all done now.
