### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#992]
As of Python 3.11.0a7 we have the following problems:

- [X] https://github.com/zopefoundation/ExtensionClass/issues/37 – Fix released in version 4.6
- [x] https://github.com/zopefoundation/Persistence/issues/28 – Fix released in version 3.3
- [x] https://github.com/zopefoundation/Acquisition/issues/59 – no release necessary
- [x] https://github.com/zopefoundation/RestrictedPython/issues/222 - Fix released as 5.3a1.dev0
- [x] https://github.com/zopefoundation/AccessControl/issues/122
- [x] https://github.com/zopefoundation/zodbpickle/pull/65
- [x] https://github.com/zopefoundation/zope.container/issues/40

Next steps:

- [ ] Run `meta/config` on `Zope` an allow future python versions. (#1030)

**Comment by dataflake** [comment]
We just need to make sure no new Zope release is done before RestrictedPython has a final release with Python 3.11 support.

**Comment by icemac** [comment]
> We just need to make sure no new Zope release is done before RestrictedPython has a final release with Python 3.11 support.

I see no problem in creating a release as we set the dependency on `RestrictedPython` to 5.2 for all Python versions except 3.11 where it is a dev release. (Currently we do not officially support Python 3.11, so this seems okay to me.)
